
version: '3.8'

services:
  redis:
    image: redis:alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
    container_name: redis
    ports:
      - "6379:6379"

  checker-microservice:
    build:
      context: C:\Users\shere\IdeaProjects\CheckerServices\Checker_microservice
      dockerfile: Dockerfile
    image: checker-microservice:latest
    container_name: checker-microservice
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://checker-microservice-db:5432/checker_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      checker-microservice-db:
        condition: service_healthy
      redis:
        condition: service_healthy

  checker-microservice-db:
    image: postgres:13
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3
    container_name: checker-microservice-db
    environment:
      POSTGRES_DB: checker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  auth-microservice:
    build:
      context: C:\Users\shere\IdeaProjects\CheckerServices\Auth_microservice
      dockerfile: Dockerfile
    image: auth-microservice:latest
    container_name: auth-microservice
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-microservice-db:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      auth-microservice-db:
        condition: service_healthy
      redis:
        condition: service_healthy

  auth-microservice-db:
    image: postgres:13
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3
    container_name: auth-microservice-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"

  frontend-microservice:
    build:
      context: C:\Users\shere\IdeaProjects\CheckerServices\Frontend_microservice
      dockerfile: Dockerfile
    image: frontend-microservice:latest
    container_name: frontend-microservice
    ports:
      - "5173:5173"
    depends_on:
      - checker-microservice
      - auth-microservice
